enum PostsActionTypes {
  FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST',
  FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED',
}

enum UsersActionTypes {
  FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS',
  FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED',
}

enum CommentsActionTypes {
  FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST',
  FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS',
  FETCH_COMMENTS_REJECTED = 'FETCH_COMMENTS_REJECTED',
}

export { PostsActionTypes, UsersActionTypes, CommentsActionTypes };
